### PR TITLE
Port Careers Section

### LINKED ISSUE #11: Port Internship section
#### Describe Problem
Port over the internship section

### LINKED ISSUE #13: port over resume section
#### Describe Problem
port over the resume section and add resume advice

### PR DESCRIPTION
**Pull request by kilbouri**
### What are you trying to accomplish?
Porting the Resume Section. There's more work to be done in a few of the subsections, but this is the bulk of the work done so it should be reviewed while pending coop advice for the remaining sections.

### How are you accomplishing it?
By converting ginger ale to markdown and JSX

### Is there anything reviewers should know?
I worked really hard on this, I hope you like it :D

- [x] Is it safe to rollback this change if anything goes wrong?
Maybe, maybe not ;)

### CODE REVIEW

**Comment by kilbouri** [comment]
The conflicts are caused by my editor auto-formatter. Either version will work.

**Review by prairir — APPROVED** [review]
LGTM

**Comment by prairir** [comment]
resolve the conflicts then il merge

**Comment by kilbouri** [comment]
Conflicts resolved

**Pull request merged**
