### PR TITLE
added search bar

### PR DESCRIPTION
**Pull request by ahmadmunim**
### What are you trying to accomplish?
Adding a search bar feature.

### How are you accomplishing it?
Downloaded a plugin from a github repo. 
Here's the link: https://github.com/cmfcmf/docusaurus-search-local

### Is there anything reviewers should know?
The search bar only works when you run 'yarn build'. It doesn't work when you run 'yarn start'. It'll be good to add this to the documentation.

### Checks before you create your pull request

-   [x] Did you read and follow article requirements?
-   [X] Did you run prettier?
-   [X] Is it safe to rollback this change if anything goes wrong?

**Images:**

search_bar_light
results_display_light
search_bar_dark
results_display_dark

### CODE REVIEW

**Comment by prairir** [comment]
Does it work with mobile? If so, please provide screenshots.

For quick "mobile" testing on desktop, please look at https://superuser.com/questions/1214829/how-can-i-view-the-mobile-version-of-a-webpage-in-google-chrome-for-desktop

**Comment by prairir** [comment]
Some basic testing with the [example site](https://christianflach.de/OpenWeatherMap-PHP-API/) shows it does work in mobile mode.

image

image

image

@ahmadmunim make sure it works in both lightmode and darkmode and pls put screenshot

**Comment by ahmadmunim** [comment]
Indeed. The search bar works on mobile mode.

**Here are the screenshots:**

search_bar_dark_mobile
search_bar_light_mobile
results_light_mobile
results_dark_mobile

**Review by prairir — APPROVED** [review]
LGTM 🚀 🚀

**Pull request merged**
