### PR TITLE
Correct prerequisites of COMP-2650

### PR DESCRIPTION
**Pull request by Hector-Zhuang**
### What are you trying to accomplish?

Correct prerequisites of COMP-2650

### How are you accomplishing it?

Because it's wrong.

### Is there anything reviewers should know?

image

### Checks before you create your pull request

-   [x] Did you read and follow article requirements?
-   [x] Did you run prettier?
-   [x] Is it safe to rollback this change if anything goes wrong?

### CODE REVIEW

**Comment by jpanahon** [comment]
image

I have fixed this in a PR I am about to make.

**Comment by angelohoeung** [comment]
> image
> 
> I have fixed this in a PR I am about to make.

Thanks Jovic!!!!

**Comment by jpanahon** [comment]
> > image
> > I have fixed this in a PR I am about to make.
> 
> Thanks Jovic!!!!

Thank you Angelo!!!!

**Comment by Hector-Zhuang** [comment]
Thanks, i'll close this first.

**Pull request closed without merging**
