### PR TITLE
finished cover letter guide

### PR DESCRIPTION
**Pull request by ahmadmunim**
### What are you trying to accomplish?

Adding and finishing cover letter guide.

### How are you accomplishing it?

Self explanatory.

### Is there anything reviewers should know?

N/A

### Checks before you create your pull request

-   [X] Did you read and follow article requirements?
-   [X] Did you run prettier?
-   [X] Is it safe to rollback this change if anything goes wrong?

### CODE REVIEW

**Comment by jere-mie** [comment]
what's up with the random added dependency?

**Comment by ahmadmunim** [comment]
> what's up with the random added dependency?

At one point, I updated npx because I got this message (image below) when I ran `yarn start`. Which is probably why it was added.

image

**Comment by jere-mie** [comment]
Makes sense

**Comment by ahmadmunim** [comment]
> Makes sense

I'm pretty sure it already existed before. But the dependency got updated.

**Review by Dante-Masciotra — APPROVED** [review]
Looks great to me 
great work!

**Comment by BorhanSaflo** [comment]
Looks good to me, great work 👏

**Review by BorhanSaflo — APPROVED** [review]
Looks good to me, great work 👏

**Pull request merged**
