### PR TITLE
changed emojis

### PR DESCRIPTION
**Pull request by bachittle**
### Did you read and follow article requirements
yes sir.

### What are you trying to accomplish?
I am tackling this issue: https://github.com/UWindsorCSS/Wiki/issues/24. Trying to change the emojis to be more memorable than the previous colored hearts. 

### How are you accomplishing it?
Changing markdown files. This is what the results look like in rendered format: 
image

### Is there anything reviewers should know?
feel free to comment if there are any emojis you think would look better. 

- [x] Is it safe to rollback this change if anything goes wrong?

### CODE REVIEW

**Comment by prairir** [comment]
is it possible to attach a photo of it in dark mode?

**Comment by bachittle** [comment]
hmmm emojis don't work on my linux machine... Maybe using fontawesome will be more versatile (and look the same on every platform). Will test that out and show what it looks like.

**Comment by bachittle** [comment]
nvm that was an issue on my part, gotta love arch. Here are the photos in light and dark mode:

image
image

now that I look at it, the photo for general and business looks similar. If there are any suggestions for what any of those 2 can be switched with, that would probably be the only 2 I would be worried about.

**Comment by prairir** [comment]
i think the heads and the people look way to similar. the graph, the wrench, and the computer are good though.

**Comment by kilbouri** [comment]
I find the graph looks strange on dark mode. What about the Abacus emoji? That's very mathematical too. Possibly more memorable, too, since you could confuse the graph with Commerce/Finances 🧮 . I'd recommend using the graph for the BA and an abacus for Math.

**Comment by bachittle** [comment]
closing due to inactivity

**Pull request closed without merging**
