### PR TITLE
Create MIT License

### PR DESCRIPTION
**Pull request by jere-mie**
### What are you trying to accomplish?
License the wiki

### How are you accomplishing it?
Add a license file

### Is there anything reviewers should know?
I'm not sure about the legality of getting this put through, whether or not we need everyone to approve to license it like we did for the hub.

### Checks before you create your pull request

-   [ ] Did you read and follow article requirements?
-   [ ] Did you run prettier?
-   [ ] Is it safe to rollback this change if anything goes wrong?

### CODE REVIEW

**Comment by prairir** [comment]
We need to check the licenses of all of our packages and get the permission of all the contributors

**Comment by kilbouri** [comment]
I'm fine with MIT, assuming the packages are all MIT+

**Review by prairir — APPROVED** [review]

**Comment by jere-mie** [comment]
I approve

**Comment by Nafiz1** [comment]
I approve

**Review by hassanuahmad — APPROVED** [review]

**Comment by Lillliant** [comment]
I approve

**Review by phucthang1101 — APPROVED** [review]
Approved 🚀 🚀

**Comment by ahmadmunim** [comment]
I approve

**Comment by BorhanSaflo** [comment]
I approve

**Pull request closed without merging**
