### PR TITLE
Change emojis on course offerings

### PR DESCRIPTION
**Pull request by ahmadmunim**
### What are you trying to accomplish?
Change the old emojis to new emojis that are distinguishable and readable based on the program.

### How are you accomplishing it?
Change the old emojis which were different colored hearts to emojis which I found to resemble the respective programs while being readable in dark mode.
General -> A stack of books 
Honours -> A graduation hat
Applied Computing -> Smartphone
Software Engineering -> A gear 
Business -> Graph 
Math -> A ruler

### Is there anything reviewers should know?
A new file called 'package-lock.json' was created and the file 'yarn.lock' was also modified but I didn't commit those files.

### Checks before you create your pull request

-   [X] Did you read and follow article requirements?
-   [X] Did you run prettier? (fingers crossed)
-   [X] Is it safe to rollback this change if anything goes wrong?

### CODE REVIEW

**Comment by prairir** [comment]
Can you give screenshots on what it looks like with lightmode and darkmode please? The emojis visibility is extremely important and was an issue with earlier suggestions

**Comment by ahmadmunim** [comment]
dark_theme
light_theme

**Comment by abdularif0705** [comment]
@ahmadmunim I think for Business and CS you can change it to one of these -> 🤵🏽💼👔

**Comment by ahmadmunim** [comment]
@abdularif0705 I was initially thinking of using 🤵 for business but I didn't find it readable in dark mode and I decided to avoid using face/person emojis all around. 💼 or 👔 could work. So I'm okay with changing the current emoji to one of those.

**Comment by abdularif0705** [comment]
👔 ok so I think this emoji would look the best for business

**Comment by ahmadmunim** [comment]
dark_theme
light_theme

**Review by prairir — APPROVED** [review]

**Review by kilbouri — APPROVED** [review]

**Pull request merged**
